url: "https://gerencserlab.github.io/Superresolution-actin-and-mitochondria-analysis/"
baseurl: "/Superresolution-actin-and-mitochondria-analysis"
relative_url: true
markdown: GFM
plugins:
  - jekyll-relative-links
gems:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false
